#include "NL/nlTextBox.h"
#include "NL/nlColour.h"

/**
 * Offset/Address/Size: 0x0 | 0x80211F28 | size: 0x244
 * TODO: 75.9% match - remaining blockers: branchless conditional (neg/or/srawi/and
 * for pMatrix ternary) not generated by MWCC for this ternary pattern, causing
 * stmw r18 vs r15 (3 missing callee-saved regs) and cascading register allocation diffs
 */
void nlTextBox::DrawString(const nlTextBox::StringDrawInfo& drawInfo, const nlVector2& pos, const nlColour& colour, eGLView view)
{
    const nlFont* pFont = drawInfo.pFont;
    int yDir = 1;
    nlVector2 CurrentPos;
    CurrentPos.as_u32[0] = pos.as_u32[0];
    CurrentPos.as_u32[1] = pos.as_u32[1];
    if (drawInfo.DrawOptions & 0x800)
    {
        yDir = -1;
    }
    float yWithOffset = CurrentPos.f.y + (float)(yDir * drawInfo.YOffset);
    CurrentPos.f.y = yWithOffset;

    int ascentAdj;
    if (drawInfo.DrawOptions & 0x200)
    {
        ascentAdj = pFont->m_Metrics.InternalLeading;
    }
    else
    {
        ascentAdj = 0;
    }

    unsigned short charAscent = pFont->m_Metrics.Ascent;
    const nlMatrix4* pMatrix = drawInfo.pMatrix;
    const char* pIter = (const char*)&drawInfo;
    int vertOffset = yDir * (int)charAscent - ascentAdj;
    nlColour overridecolour;
    overridecolour = colour;
    bool flipY = (drawInfo.DrawOptions >> 11) & 1;
    float startX = pos.f.x;
    unsigned long hMatrix;
    overridecolour.c[3] = 0;

    const unsigned short* pString = drawInfo.String;
    unsigned long row = 0;
    unsigned short rowCount = drawInfo.RowCount;
    CurrentPos.f.y = yWithOffset + (float)vertOffset;

    for (; row < rowCount; row++)
    {
        const Row* CurrentRow = (const Row*)(pIter + 0x14);
        CurrentPos.f.x = startX + (float)CurrentRow->XOffset;

        if (pMatrix != (const nlMatrix4*)0)
        {
            unsigned long h = glAllocMatrix();
            if (h + 0x10000 != 0xFFFF)
            {
                glSetMatrix(h, *pMatrix);
            }
            hMatrix = h;
        }

        unsigned short startIdx = CurrentRow->FirstChar;
        FontCharString fontCharStr;
        fontCharStr.m_InternalBuffer = 0;
        fontCharStr.m_pString = (unsigned short*)(pString + startIdx);

        int length = (int)(CurrentRow + 1)->FirstChar - (int)startIdx;
        unsigned long* matArg = pMatrix ? &hMatrix : (unsigned long*)0;

        drawInfo.pFont->DrawString(view, fontCharStr, CurrentPos, colour, colour, length, nlFont::PASS_TextAndEffect, flipY, matArg, &overridecolour);

        if (fontCharStr.m_InternalBuffer)
        {
            delete[] fontCharStr.m_pString;
        }
        if (!overridecolour.c[3])
        {
            overridecolour = colour;
        }

        CurrentPos.f.y += (float)(yDir * (int)pFont->m_Metrics.Height);
        pIter += 4;
    }
}

/**
 * Offset/Address/Size: 0x244 | 0x8021216C | size: 0x3B0
 */
void nlTextBox::ProcessString(const FontCharString*, const nlFont*, const nlVector2&, unsigned long, const nlMatrix4*, nlTextBox::StringDrawInfo&)
{
}
