#ifndef _SCRIPTQUESTIONS_H_
#define _SCRIPTQUESTIONS_H_

#include "NL/nlMath.h"
#include "Game/Player.h"
#include "Game/Ball.h"
#include "Game/Team.h"
#include "Game/Game.h"
#include "Game/AI/Fielder.h"

float InOffensiveZoneOfPlayer(cBall*, cPlayer*);
float InDefensiveZoneOfPlayer(cBall*, cPlayer*);
float InOffensiveZone(cPlayer*);
float InDefensiveZone(cPlayer*);
float InOffensiveZone(const nlVector3&, eTeamSide);
void Difficult(cTeam*);
void TimeFarFromOver(cGame*);
void TimeNearlyOver(cGame*);
void TimeCloseToOver(cGame*);
void PerfectPassCandidateFrom(cFielder*, cFielder*);
void IsPerfectPassInPlay();
void IsPassInPlayDelayed();
void Stalling(cTeam*);
void Loose(cTeam*);
void Defensive(cTeam*);
void Offensive(cTeam*);
void Winning(cTeam*);
void Tied(cTeam*);
void Losing(cTeam*);
void GonnaGetBall(cTeam*);
void UserControlledT(cTeam*);
void Passive(cTeam*);
void Moderate(cTeam*);
void AggressiveT(cTeam*);
void Ownerless(cBall*);
void High(cBall*);
void ReceivingVolleyPassDelayed(cPlayer*);
void PassReceiveCloseToDone(cFielder*);
void ReceivingPassDelayed(cFielder*);
void ReceivingVolleyPass(cPlayer*);
void ReceivingPass(cFielder*);
void ChasingBall(cPlayer*);
void OnMushrooms(cFielder*);
void WindingUpForShot(cFielder*);
void InControlOfBall(cFielder*);
void NearToPlayersNet(cBall*, cPlayer*);
void FarToTheirNetB(cBall*);
void Stunned(Goalie*);
void OutOfNet(Goalie*);
void SeparatingFrom(cPlayer*, cPlayer*);
void ClosingTo(cPlayer*, cBall*);
void ClosingTo(cPlayer*, cPlayer*);
void DownfieldFrom(cPlayer*, cPlayer*);
void UpfieldFrom(cPlayer*, cPlayer*);
void Facing(cPlayer*, cPlayer*);
float PositionIsAtIdealDistanceForShooting(const nlVector3&, const nlVector3&);
void AtIdealDistanceForTackling(cPlayer*, cPlayer*);
void StuckOnSidelines(cFielder*);
void FacingSideline(cFielder*);
void CloseToSideline(cFielder*);
float NearToSideline(const nlVector3&);
float CloseToSideline(const nlVector3&, const nlVector2*, bool);
void FarToTheirGoalie(cPlayer*);
void NearToTheirGoalie(cPlayer*);
void CloseToTheirGoalie(cPlayer*);
float NearToGoaliePosition(const nlVector3&, const nlVector3&);
void FarTo(cPlayer*, cPlayer*);
void NearTo(cPlayer*, cPlayer*);
void CloseTo(cPlayer*, cPlayer*);
void OpenTo(cPlayer*, cPlayer*);
void InBetweenMyNetAnd(cFielder*, cBall*);
void InBetweenMyNetAnd(cFielder*, cFielder*);
void OpenToMyNet(cFielder*);
void OpenToTheirNet(cFielder*);
void WideOpen(cFielder*);
void Open(cFielder*);
float WideOpenPosition(const nlVector3&, cTeam*, cPlayer*);
float OpenPosition(const nlVector3&, cTeam*, cPlayer*, const nlVector2*);
float OpenToPosition(const nlVector3&, const nlVector3&, const cTeam*, const cPlayer*, const cPlayer*, bool);
void OnBreakaway(cFielder*);
void InFrontOfTheirNet(cFielder*);
float PositionIsInFrontOfNet(const nlVector3&, const cNet*);
void GoalieOutOfPosition(cFielder*);
void LikelyToScore(cFielder*);
void PlayerShotDistance(cFielder*);
float LikelyToScoreFromPosition(const nlVector3&, const nlVector3&, const cNet*, bool);
void FallenDown(cFielder*);
void Frozen(cFielder*);
void Incapacitated(cPlayer*);
void Invincible(cFielder*);
void AvoidingPowerups(cFielder*);
void Attacked(cFielder*);
void Pressured(cFielder*);
void FarToTheirNet(cPlayer*);
void NearToTheirNet(cPlayer*);
void CloseToTheirNet(cPlayer*);
void FarToMyNet(cPlayer*);
void NearToMyNet(cPlayer*);
void CloseToMyNet(cPlayer*);
void FarToBall(cPlayer*);
void NearToBall(cPlayer*);
void CloseToBall(cPlayer*);
void LikelyToUsePowerup(cFielder*, int);
void AbleToUsePowerup(cFielder*, int);
void AbleToInterceptBallForSwapController(cFielder*);
float AbleToInterceptBall(cPlayer*);
// void RepeatingLastDesire(cFielder*, eScriptFielderDesire);
void Deker(cFielder*);
void Passer(cFielder*);
void Shooter(cFielder*);
void Aggressive(cFielder*);
void InPassingLane(cFielder*);
void UserControlled(cFielder*);
void StrategicBallOwner(cFielder*);
void OnTheGround(cPlayer*);
void OnScreen(cPlayer*);
void OnTheirTeam(cFielder*);
void Marking(cFielder*, cPlayer*);
void GoalieType(cPlayer*);
void Captain(cFielder*);
void Defence(cFielder*);
void Midfield(cFielder*);
void Winger(cFielder*);
void Striker(cFielder*);
void LastBallOwner(cPlayer*);
void BallOwnerT(cTeam*);
void BallOwner(cPlayer*);
void CalcSelectChance(float, float);
// void PositionOf<cBall*>(cBall*);
// void PositionOf<cPlayer*>(cPlayer*);

#endif // _SCRIPTQUESTIONS_H_
